
-- =========================       Users Table        =========================

CREATE TABLE users (
    -- Recommended way for auto-incrementing PK in modern PostgreSQL
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Alternatively, the traditional way:
    -- id SERIAL PRIMARY KEY,
    
    username VARCHAR(50),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    jwt_token TEXT,
    otp_code VARCHAR(10),
    otp_expires_at TIMESTAMP,
    -- Removed NULL constraint and added a comma
    verified_at TIMESTAMP, 
    
    -- In PostgreSQL, boolean defaults should be TRUE or FALSE, not 0 or 1
    is_frozen BOOLEAN DEFAULT FALSE,
    attempt INTEGER DEFAULT 0,
    is_oauth BOOLEAN DEFAULT FALSE,
    oauth_access_token TEXT,
    oauth_refresh_token TEXT,
    -- JSON is a standard PostgreSQL type
    oauth_profile_data JSON, 
    is_verified BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    
    -- DATETIME is usually TIMESTAMP WITHOUT TIME ZONE in Postgres,
    -- and CURRENT_TIMESTAMP is equivalent to NOW()
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    -- Removed the trailing comma before the closing parenthesis
);

ALter TABLE usermgmt.users ADD COLUMN is_admin BOOLEAN  DEFAULT FALSE


CREATE TABLE organization(

   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   admin_id int,
   org_id varchar(5)  NOT NULL UNIQUE,
   org_name varchar(30) NOT NULL,

FOREIGN KEY (admin_id) REFERENCES usermgmt.users(id)
   
);

ALTER TABLE organizationmgmt.organization 
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN  is_deleted BOOLEAN DEFAULT FALSE;




CREATE TABLE usermgmt.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id INT,
    user_id INT,
    roles VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,

    -- Correct CHECK syntax
    CONSTRAINT role_check CHECK (roles IN ('owner', 'admin', 'sales', 'delivery')),

    -- Correct FK syntax with commas
    CONSTRAINT fk_roles_org FOREIGN KEY (org_id)
        REFERENCES organizationmgmt.organization(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_roles_user FOREIGN KEY (user_id)
        REFERENCES usermgmt.users(id)
        ON DELETE CASCADE
);

ALTER TABLE usermgmt.roles ADD COLUMN status BOOLEAN DEFAULT FALSE;